"""Generated by experiments/derive_egb_rotating.py; do not edit by hand.

The four horizon regularity relations in the spectral-solver-ready compact
variables (B,F,H,W,P=Bx,Q=Hx,V=Wx at x=0, plus Fx and Wxx supplied by the
solver's own differentiation matrix at that node -- see
compact_horizon_conditions in derive_egb_rotating.py and docs/egb-rotating.md).
Zero iff the represented solution is regular at the horizon.
"""

def horizon(B_H, F_H, H_H, W_H, P, Q, V, Fx, Wxx, alpha_gb):
    """Return the four raw-equation residuals (from eqs b,g,h,w)."""
    k0 = H_H + 1
    k1 = 12*B_H
    k2 = B_H*H_H
    k3 = 8*k2
    k4 = F_H*k1
    k5 = 2*B_H
    k6 = F_H*Q
    k7 = 4*B_H
    k8 = F_H*k7
    k9 = V**2
    k10 = F_H*k9
    k11 = alpha_gb*k10
    k12 = W_H**2
    k13 = F_H*k12
    k14 = alpha_gb*k13
    k15 = H_H**2
    k16 = k14*k15
    k17 = H_H**3
    k18 = 192*k14
    k19 = k17*k18
    k20 = H_H*k13
    k21 = alpha_gb*k20
    k22 = V*W_H
    k23 = F_H*k22
    k24 = alpha_gb*k23
    k25 = 32*k24
    k26 = k10*k15
    k27 = alpha_gb*k26
    k28 = 12*k11
    k29 = k17*k28
    k30 = H_H*k10
    k31 = alpha_gb*k30
    k32 = 8*F_H
    k33 = B_H*alpha_gb
    k34 = F_H*k33
    k35 = k15*k34
    k36 = alpha_gb*k2*k6
    k37 = 16*k13
    k38 = k22*k32
    k39 = 48*k34
    k40 = 16*H_H
    k41 = k10 + k15*k37 - k15*k38 + k15*k7 + 32*k20 - k23*k40 + k26 + 2*k30 + k37 - k38 + k39
    k42 = F_H*P
    k43 = 6*k42
    k44 = Fx*k5
    k45 = alpha_gb*k42
    k46 = 24*k45
    k47 = Fx*k33
    k48 = 8*k47
    k49 = F_H**2
    k50 = alpha_gb*k49
    k51 = k50*k9
    k52 = 8*k51
    k53 = k33*k49
    k54 = 32*k53
    k55 = k12*k50
    k56 = 128*k55
    k57 = F_H*k2
    k58 = alpha_gb*k57
    k59 = -96*F_H*V*W_H*alpha_gb + k18 + k28
    k60 = 24*k23
    k61 = F_H*V
    k62 = Fx*V*k7
    k63 = 16*W_H
    k64 = 4*V*k42
    k65 = k42*k63
    k66 = k2*k61
    k67 = 192*W_H
    k68 = 48*k6
    k69 = 256*W_H
    k70 = Fx*k2
    k71 = 16*V
    k72 = 64*W_H
    k73 = alpha_gb*k70
    k74 = 32*V
    k75 = 128*W_H
    k76 = H_H*k45
    k77 = 64*V
    k78 = k2*k50
    k79 = k15*k47
    k80 = 48*V
    k81 = k15*k45
    return (2*k0*(H_H*k25 + H_H*k8 + Q*k32*k33 - k1 + 4*k11 + 64*k14 + 160*k15*k24 - 320*k16 + 96*k17*k24 - k19 - 64*k21 - k25 - 20*k27 - k29 - k3 - 4*k31 + 80*k35 - 24*k36 + k4 + k41 + k5*k6), -k0*k7*(4*B_H*F_H*Q + 16*B_H*Fx*H_H*alpha_gb + 2*B_H*Fx*H_H + 8*B_H*Fx*alpha_gb*k15 + 32*B_H*H_H*alpha_gb*k49 + 48*F_H*H_H*P*alpha_gb + 6*F_H*H_H*P + 288*F_H*H_H*V*W_H*alpha_gb + 24*F_H*P*alpha_gb*k15 + 288*F_H*V*W_H*alpha_gb*k15 + 96*F_H*V*W_H*alpha_gb*k17 + 128*H_H*V*W_H*alpha_gb*k49 - H_H*k4 - 256*H_H*k55 - 16*Q*k53 + 64*V*W_H*alpha_gb*k15*k49 + 64*V*W_H*alpha_gb*k49 - k15*k39 - k15*k52 - k15*k56 - 576*k16 - k19 - 576*k21 - 36*k27 - k29 - k3 - 36*k31 - k40*k51 - k41 + k43 + k44 + k46 + k48 - k52 - k54 - k56 - 96*k58 - k59 - k7 + k8), k7*(24*B_H*Fx*H_H*alpha_gb + 72*F_H*H_H*P*alpha_gb + 576*F_H*H_H*V*W_H*alpha_gb + 48*F_H*H_H*k12 + 3*F_H*H_H*k9 + 480*F_H*V*W_H*alpha_gb*k15 + 48*F_H*k12 + 3*F_H*k9 - H_H*k1 - H_H*k60 - 960*k16 - 1152*k21 - 60*k27 - 72*k31 + k39 - k43 - k44 - k46 - k48 + k54 - 144*k58 - k59 - k60 + k7 - k8), B_H*Fx*k63 + B_H*W_H*k68 - B_H*Wxx*k32 + 40*B_H*k61 - F_H*Wxx*k3 - H_H*k62 + H_H*k64 - H_H*k65 - Q*V*k4 + V*k33*k68 + 224*V*k34 - 1632*V*k35 + 240*V*k36 + 4608*W_H*k35 - 960*W_H*k36 + 1280*W_H*k58 - 32*Wxx*k34 + 96*Wxx*k35 + 64*Wxx*k58 - 640*alpha_gb*k66 - k33*k6*k67 - k34*k69 + k45*k71 - k45*k72 - k47*k71 + k47*k72 - k53*k69 + k53*k77 - k57*k67 - k62 + k63*k70 + k64 - k65 + 88*k66 - k67*k79 + k67*k81 - k69*k78 + k73*k74 - k73*k75 - k74*k76 + k75*k76 + k77*k78 + k79*k80 - k80*k81)
