"""Generated by experiments/derive_egb_rotating.py; do not edit by hand.

The five raw Euler-Lagrange variations (post gauge g=r^2), for
validation and tests only -- E_f is the reserved constraint
(never solved for; see docs/vacuum-bvp.md for the Hito 2 analogue
and docs/egb-rotating.md for this one). fpp is accepted but unused
(matches vacuum_equations.radial_equations).
"""

def equations(r, values, first, second, alpha_gb):
    """Return E_b,E_f,E_g,E_h,E_w; zero iff values solve the EGB system.

    values=(b,f,h,w), first=(bp,fp,hp,wp), second=(bpp,fpp,hpp,wpp).
    """
    b, f, h, w = values
    bp, fp, hp, wp = first
    bpp, fpp, hpp, wpp = second
    e0 = h**3
    e1 = r**6
    e2 = b*fp
    e3 = e2*h
    e4 = h**2
    e5 = r**4
    e6 = r**2
    e7 = 4*b*e0
    e8 = 16*b
    e9 = alpha_gb*e8
    e10 = e9*fp
    e11 = 4*b
    e12 = e11*hp
    e13 = r**5
    e14 = e13*f
    e15 = e14*h
    e16 = e1*f
    e17 = 2*b
    e18 = h*hpp
    e19 = e5*f
    e20 = e11*e4
    e21 = hp**2
    e22 = b*e19
    e23 = e4*r
    e24 = alpha_gb*f
    e25 = b*e24
    e26 = e25*hp
    e27 = e5*fp
    e28 = wp**2
    e29 = e0*e28
    e30 = f**2
    e31 = b*e21
    e32 = alpha_gb*e30
    e33 = 4*e32
    e34 = h**4
    e35 = 1/(e4*e5)
    e36 = b**2
    e37 = 1/e36
    e38 = (1/4)*e37
    e39 = 1/h
    e40 = r**3
    e41 = 1/e40
    e42 = e40*h
    e43 = e42*e8
    e44 = bp*hp
    e45 = 16*e24
    e46 = bp*e4
    e47 = e11*f
    e48 = 12*h
    e49 = e40*e44
    e50 = e28*e4
    e51 = 12*e32
    e52 = 12*e24
    e53 = e40*e50
    e54 = alpha_gb*fp
    e55 = bp**2
    e56 = bp*e2
    e57 = e36*h
    e58 = e57*hp
    e59 = e40*f
    e60 = 2*e4
    e61 = bpp*e22
    e62 = e36*e40*fp
    e63 = bp*e40
    e64 = 2*e32
    e65 = e63*e64
    e66 = (1/2)*e37
    e67 = 48*wp
    e68 = bp*wp
    return (e35*e38*(96*alpha_gb*b*e0*f + 16*alpha_gb*b*e21*e5*f + 12*alpha_gb*b*e21*e6*f*h + 8*alpha_gb*b*e30*e5*h*hpp + 24*alpha_gb*b*e4*e6*f*hpp + 12*alpha_gb*b*e4*e6*fp*hp + 12*alpha_gb*b*e5*f*fp*h*hp + 4*alpha_gb*e0*e28*e30*e5 - 32*alpha_gb*e18*e22 - 16*alpha_gb*e19*e29 + 12*alpha_gb*e28*e34*e6*f + b*e1*e21*f + 16*b*e4*e5 - e0*e10*r - e1*e3*hp - e12*e15 - e13*e20*fp - e16*e17*e18 - e16*e29 - e19*e20 - 96*e23*e26 - e27*e9*h*hp - e31*e33*e5 - e6*e7), (1/4)*e39*e41*(4*bp*e19*h + e11*e23 + e12*e19 + e14*e44 + e14*e50 - e24*e44*e48*r - e29*e52*r + e42*e47 - e43 + e45*e46 + e45*e49 + e45*e53 - e49*e51 - e51*e53)/(b*f), e35*e66*(4*alpha_gb*b*bp*e30*e40*h*hpp + 6*alpha_gb*b*bp*e40*f*fp*h*hp + 4*alpha_gb*b*bpp*e30*e40*h*hp + 6*alpha_gb*b*e0*e28*e40*f*fp + 8*alpha_gb*b*e0*e30*e40*wp*wpp + 6*alpha_gb*b*e28*e30*e4*e40*hp + 12*alpha_gb*b*e28*e34*f + 4*alpha_gb*e0*e55*f + b*e0*e28*e5*f - bp*e54*e7 - 8*bpp*e0*e25 + 4*e0*e36 - e17*e46*e59 - 2*e19*e57*hpp + e21*e36*e5*f - e22*e44*h - e27*e58 - e29*e65 - e31*e65 + e4*e5*e55*f - e4*e5*e56 - e42*e55*e64*hp - 2*e58*e59 - e60*e61 - e60*e62), e38*e39*(12*alpha_gb*b*bp*e6*f*fp + 12*alpha_gb*b*bp*fp*h + 8*alpha_gb*b*bpp*e30*e6 + 24*alpha_gb*b*bpp*f*h + 48*alpha_gb*b*e28*e6*f*h + 16*alpha_gb*e55*e6*f - b*e28*e32*e48*e6 + 3*b*e28*e5*f*h - bp*e10*e6 - 32*bpp*e25*e6 - e24*e48*e55 - 60*e25*e50 - e33*e55*e6 - 4*e36*e6*f + 16*e36*e6 - e47*e63 + e5*e55*f - e5*e56 - 12*e57 - 2*e61 - 4*e62)/e6, e41*e66*(8*alpha_gb*b*e30*e40*h*wpp + 12*alpha_gb*b*e30*e40*hp*wp + 24*alpha_gb*b*e4*f*r*wpp + 12*alpha_gb*b*e4*fp*r*wp + 12*alpha_gb*b*e40*f*fp*h*wp + 60*alpha_gb*b*f*h*hp*r*wp + 16*alpha_gb*bp*e40*f*h*wp - 3*b*e14*hp*wp + bp*e13*f*h*wp - e11*e19*h*wp - e13*e3*wp - e15*e17*wpp - e23*e52*e68 - e25*e4*e67 - 32*e25*e42*wpp - e26*e40*e67 - e33*e42*e68 - e43*e54*wp))
