"""Generated by experiments/derive_near_horizon.py; do not edit by hand.

Extremal near-horizon entropy function for D=5 equal-spin EGB, in the
homogeneous ansatz of that script. `scalar` and `density` are R and L_GB,
checked there against einstein.py; `stationarity` are the three numerators
of df/dv_i, whose common root with v1=1 is the extremal near-horizon.
"""

import numpy as np


def scalar(v1, v2, v3, k):
    """Ricci scalar; constant on the near-horizon geometry."""
    return (1/8)*k**2*v3/v1**2 + 8/v2 - 2*v3/v2**2 - 2/v1


def density(v1, v2, v3, k):
    """Gauss-Bonnet density; also constant."""
    return (1/2)*(4*k**2*v2*v3 - 3*k**2*v3**2 - 64*v1*v2 + 16*v1*v3)/(v1**2*v2**2)


def entropy_function(v1, v2, v3, k, alpha_gb):
    """f = (pi/8) v1 v2 sqrt(v3) (R + alpha_GB L_GB)."""
    return (np.pi/8)*v1*v2*np.sqrt(v3)*(scalar(v1, v2, v3, k)
                                        + alpha_gb*density(v1, v2, v3, k))


def stationarity(v2, v3, k, alpha_gb, v1=1.0):
    """Numerators of df/dv1, df/dv2, df/dv3; zero on the extremal solution."""
    return (
        -16*alpha_gb*k**2*v2*v3**(3/2) + 12*alpha_gb*k**2*v3**(5/2) - k**2*v2**2*v3**(3/2) + 64*v1**2*v2*np.sqrt(v3) - 16*v1**2*v3**(3/2),
        12*alpha_gb*k**2*v3**(5/2) - 64*alpha_gb*v1*v3**(3/2) + k**2*v2**2*v3**(3/2) + 16*v1**2*v3**(3/2) - 16*v1*v2**2*np.sqrt(v3),
        48*alpha_gb*k**2*v2*v3 - 60*alpha_gb*k**2*v3**2 - 256*alpha_gb*v1*v2 + 192*alpha_gb*v1*v3 + 3*k**2*v2**2*v3 + 64*v1**2*v2 - 48*v1**2*v3 - 16*v1*v2**2,
    )
