"""Generated by experiments/derive_static_egb.py; do not edit by hand."""

def rhs(z, F, alpha_hat):
    """Return Fx=dF/dx for the static EGB ansatz; z=1-x=r_H/r."""
    return 2*(1 - F)/(z*(4*alpha_hat*z**2*(1 - F) + 1))
