"""Generated by pw_generator.py; do not edit."""
import numpy as np
from numpy import sqrt, pi

def J_of(xi, P1, P1x, P2, P2x, P3, P3x, W, Wx, alpha):
    x0 = 8*xi
    x1 = xi**2
    x2 = 14*x1
    x3 = xi**3
    x4 = 12*x3
    x5 = xi**4
    x6 = 5*x5
    x7 = -x0 + x2 - x4 + x6 + 2
    x8 = x7**(-1.0)
    x9 = 28*xi
    x10 = sqrt(2)
    x11 = 12*x10
    x12 = 20*x3
    x13 = 4*x3
    x14 = x10*x13
    x15 = 4*xi
    x16 = x8*(-36*W*x1 + W*x12 + W*x9 - 8*W - Wx*x0 + Wx*x2 - Wx*x4 + Wx*x6 + 2*Wx - x1*x11 - 4*x10 + x11*xi + x14) + (36*x1 - x12 - x9 + 8)*(-W*x0 + W*x2 - W*x4 + W*x6 + 2*W + 6*x1*x10 - x10*x15 + x10*x5 + x10 - x14)/x7**2
    x17 = 2*P2
    x18 = P2*P3
    x19 = (P3*x17 - x0*x18 + x18*x2 - x18*x4 + x18*x6)/(7*x1 - x15 - 6*x3 + 2*x5 + 1)
    x20 = 2*xi
    x21 = x1 - x20 + 1
    x22 = x21**(-1.0)
    x23 = -P2*x20 + P2 + x1*x17
    x24 = 2*x1
    x25 = (x1 - x13 + 6*x5 + xi**6 - 4*xi**5)/(-P1*x20 + P1*x24 + P1)
    x26 = sqrt(x25)/sqrt(P1*x5*x8)
    x27 = x16*x19
    return -1/16*pi*(alpha*sqrt(x19)*x21*x26*(-x25*x27*(x22*(P2*x15 - P2x*x20 + P2x*x24 + P2x - x17) + x23*(2 - x20)/x21**2)**2 + 2*x27*(-6*x19 + 8*x22*x23))/x23 + x16*x19**(3/2)*x22*x23*x26)
