"""Compactified field equations for an EXTREMAL horizon (double zero), gauge
g = r^2, r_H = 1, generated as NumPy code.

Variables (z = 1/r, x = 1 - z; x = 0 horizon, x = 1 infinity):
    b = (1-z^2)^2 B,  f = (1-z^2)^2 F,  h = (1 + z^4 H)/z^2,  w = z^4 W .
Extremal Myers-Perry is B = 1/(1+z^4), F = 1, H = 1, W = sqrt(2)/(1+z^4).

The four equations E_b, E_g, E_h, E_w of derive.py (E_f is the constraint,
kept as a diagnostic) are divided by sqrt(b h/f), written in x, and reduced to
their polynomial numerators. Each numerator is divided by the largest power of
x that divides it for *generic* jets, so the residual is finite and generically
non-zero at the horizon node, where it reduces to the near-horizon relations.

Checks (asserted):
  * extremal Myers-Perry solves all five residuals identically (symbolic);
  * at x = 0 the residuals, evaluated on near-horizon data, vanish for the
    near-horizon solution of nearhorizon.py at finite coupling.

Output: _extremal_generated.py with residual(x, jets..., alpha) and
constraint(x, jets..., alpha).
"""
import pickle
from pathlib import Path

import sympy as sp

HERE = Path(__file__).resolve().parent

X = sp.Symbol('x')
ALPHA = sp.Symbol('alpha')
NAMES = ('B', 'Bx', 'Bxx', 'F', 'Fx', 'H', 'Hx', 'Hxx', 'W', 'Wx', 'Wxx')
JET = sp.symbols(' '.join(NAMES))
J = dict(zip(NAMES, JET))


def load():
    with open(HERE/'equations.pkl', 'rb') as handle:
        return pickle.load(handle)['eq']


def compact(eq):
    """E_v / sqrt(b h / f) as rational functions of x and the jets."""
    r = eq['r']
    z = 1-X
    Bf, Ff, Hf, Wf = (sp.Function(n)(X) for n in 'BFHW')
    phys = dict(b=(1-z**2)**2*Bf, f=(1-z**2)**2*Ff, g=1/z**2,
                h=(1+z**4*Hf)/z**2, w=z**4*Wf)
    d_dr = lambda e: z**2*sp.diff(e, X)          # d/dr = z^2 d/dx
    subs = {}
    for k in 'bfghw':
        subs[sp.diff(eq[k], r, 2)] = d_dr(d_dr(phys[k]))
    for k in 'bfghw':
        subs[sp.diff(eq[k], r)] = d_dr(phys[k])
    for k in 'bfghw':
        subs[eq[k]] = phys[k]
    jet_subs = {}
    for n, fn in zip('BFHW', (Bf, Ff, Hf, Wf)):
        jet_subs[sp.diff(fn, X, 2)] = J.get(n+'xx', sp.Symbol(n+'xx'))
    for n, fn in zip('BFHW', (Bf, Ff, Hf, Wf)):
        jet_subs[sp.diff(fn, X)] = J[n+'x']
    for n, fn in zip('BFHW', (Bf, Ff, Hf, Wf)):
        jet_subs[fn] = J[n]
    out = {}
    for name in ('b', 'g', 'h', 'w', 'f'):
        # normalise while b, f, h are still positive functions, so that the
        # square roots split and cancel before anything is substituted
        e = sp.expand(eq['E'][name]/sp.sqrt(eq['b']*eq['h']/eq['f']))
        assert not any(not p.exp.is_integer for p in e.atoms(sp.Pow)), name
        e = e.subs(subs, simultaneous=True).subs(r, 1/z)
        e = e.subs(jet_subs, simultaneous=True)
        e = sp.together(sp.powsimp(sp.powdenest(e, force=True), force=True))
        num, den = sp.fraction(e)
        num = sp.expand(num)
        assert not any(not p.exp.is_integer for p in num.atoms(sp.Pow)), name
        out[name] = (num, den)
    return out


def strip_x(num):
    """Divide by the largest powers of x and of z = 1 - x that divide the
    numerator identically (for generic jets). Without the z-stripping the rows
    near infinity are nearly empty and the collocation matrix is near-singular
    there."""
    poly = sp.Poly(num, X)
    low = min(m[0] for m in poly.monoms())
    num = sp.expand(sp.cancel(num/X**low))
    Z = sp.Symbol('z')
    in_z = sp.Poly(sp.expand(num.subs(X, 1-Z)), Z)
    low_z = min(m[0] for m in in_z.monoms())
    num = sp.expand(sp.cancel(sp.expand(num.subs(X, 1-Z))/Z**low_z).subs(Z, 1-X))
    return num, (low, low_z)


def main():
    eq = load()
    alpha = eq['alpha']
    raw = compact(eq)
    residuals, powers = {}, {}
    for name, (num, den) in raw.items():
        num = num.subs(alpha, ALPHA)
        stripped, low = strip_x(num)
        residuals[name] = stripped
        powers[name] = low
        print(f'E_{name}: numerator divisible by x^{low}; residual has '
              f'{len(sp.Add.make_args(stripped))} terms')
    # Myers-Perry check, exact
    z = 1-X
    mp = {'B': 1/(1+z**4), 'F': sp.Integer(1), 'H': sp.Integer(1), 'W': sp.sqrt(2)/(1+z**4)}
    mp_jets = {}
    for n in 'BFHW':
        mp_jets[J[n]] = mp[n]
        mp_jets[J[n+'x']] = sp.diff(mp[n], X)
        if n+'xx' in J:
            mp_jets[J[n+'xx']] = sp.diff(mp[n], X, 2)
    for name, e in residuals.items():
        value = sp.simplify(e.subs(mp_jets).subs(ALPHA, 0))
        assert value == 0, (name, value)
    print('extremal Myers-Perry solves all five residuals identically at alpha=0: OK')
    args = (X, *JET, ALPHA)
    code = ['"""Generated by extremal_equations.py; do not edit."""',
            'import numpy as np', 'from numpy import sqrt', '']
    for name in ('b', 'g', 'h', 'w', 'f'):
        fn = sp.lambdify(args, residuals[name], modules='numpy', cse=True)
        import inspect
        src = inspect.getsource(fn).replace('def _lambdifygenerated', f'def E_{name}')
        code.append(src)
    code.append('def residual(' + ', '.join(str(a) for a in args) + '):')
    code.append('    return (' + ', '.join(f'E_{n}(' + ', '.join(str(a) for a in args) + ')'
                                       for n in ('b', 'g', 'h', 'w')) + ')')
    code.append('')
    code.append('def constraint(' + ', '.join(str(a) for a in args) + '):')
    code.append('    return E_f(' + ', '.join(str(a) for a in args) + ')')
    code.append(f'POWERS = {powers!r}')
    (HERE/'_extremal_generated.py').write_text('\n'.join(code)+'\n')
    with open(HERE/'extremal_residuals.pkl', 'wb') as handle:
        pickle.dump(dict(residuals=residuals, powers=powers, args=args), handle)
    print('wrote _extremal_generated.py')


if __name__ == '__main__':
    main()
