"""Generate report/numbers.tex (macros) and report tables from the results.

No number in report/report.tex is typed; every one is a macro written here
from: nearhorizon.json, convergence_rq.json, branch_rq.json, analysis.json,
polished.json, kkr_curves.json, digitised.json, gamma_check.json.

Run: python make_report_numbers.py
"""
import json
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
OUT = HERE/'report'


def sci(v, d=1):
    if v == 0:
        return '0'
    m, e = f'{v:.{d}e}'.split('e')
    e = int(e)
    return m if e == 0 else rf'{m}\times10^{{{e}}}'


def fx(v, d):
    return f'{v:.{d}f}'


def main():
    OUT.mkdir(exist_ok=True)
    L = ['% generated by make_report_numbers.py; do not edit']

    def mac(name, body):
        L.append(rf'\newcommand{{\R{name}}}{{{body}}}')

    # ---------------------------------------------------------- near horizon
    nh = json.loads((HERE/'nearhorizon.json').read_text())
    gam = [max(r['exponents']) for r in nh if r['alpha'] > 0]   # the growing mode
    ys = [r['y'] for r in nh if r['alpha'] > 0]
    k = int(np.argmin(gam))
    mac('gammamin', fx(gam[k], 3))
    mac('gammaminy', fx(ys[k], 3))
    mac('gammaymax', fx(max(ys), 1))
    g, yy = np.array(gam), np.array(ys)
    for target, name in ((2., 'two'), (3., 'three')):
        i = np.where((g[:-1]-target)*(g[1:]-target) < 0)[0]
        i = i[-1]                               # the upward crossing at larger y
        yc = yy[i]+(target-g[i])*(yy[i+1]-yy[i])/(g[i+1]-g[i])
        mac(f'gammacross{name}', fx(yc, 2))
    mac('gammasmally', fx(min(y for y in ys if y > 0), 4))
    # --------------------------------------------------------- digitisation
    dig = json.loads((HERE/'digitised.json').read_text())
    exact = {'xjaH-MP2': lambda x: (1-x)**1.5, 'xjtH-MP2': lambda x: np.sqrt(1-x)/(1+x)}
    worst = 0
    for key, fn in exact.items():
        pts = np.array([q for p in dig[key]['paths'] if p['plot'] == 0 and p['colour'] == [0, 0, 1.0]
                        and p['kind'] == 'stroke' and len(p['points']) > 3 for q in p['points']])
        pts = pts[pts[:, 0] <= 1]
        worst = max(worst, np.max(np.abs(pts[:, 1]-fn(pts[:, 0]))))
    mac('digitworst', sci(worst))
    # ---------------------------------------------------------- convergence
    conv = json.loads((HERE/'convergence_rq.json').read_text())
    for c in conv:
        tag = {0.05: 'a', 0.2: 'b', 0.5: 'c'}[c['alpha']]
        row96 = next(r for r in c['rows'] if r['n'] == 96)
        mac(f'conv{tag}alpha', f"{c['alpha']:g}")
        mac(f'conv{tag}mu', fx(row96['mu'], 7))
        mac(f'conv{tag}mums', fx(c['manuscript']['mu'], 7))
        mac(f'conv{tag}y', fx(row96['y'], 7))
        mac(f'conv{tag}yms', fx(c['manuscript']['y'], 7))
    # -------------------------------------------------------------- branch
    br = json.loads((HERE/'branch_rq.json').read_text())
    rows = [r for r in br['rows'] if r['alpha'] > 0]
    hi = [r['high'] for r in rows]
    mac('branchpoints', str(len(rows)))
    mac('alphamax', fx(rows[-1]['alpha'], 3))
    mac('ymax', fx(hi[-1]['y'], 3))
    mac('xmax', fx(hi[-1]['x'], 3))
    mac('jlast', fx(hi[-1]['j'], 3))
    mac('nmaxbranch', str(max(r.get('n_high', br['n_high']) for r in rows)))
    mac('constraintworst', sci(max(h['constraint'] for h in hi)))
    lo = [r['low'] for r in rows]
    mac('dmuworst', sci(max(abs(a['mu']-b['mu']) for a, b in zip(hi, lo))))
    mac('dslopeworst', sci(max(abs(a['mu_prime']-b['mu_prime']) for a, b in zip(hi, lo))))
    # identities over the rows whose two resolutions agree (|dmu|, |dmu'| < 1e-5)
    clean = [(r, a, b) for r, a, b in zip(rows, hi, lo)
             if abs(a['mu']-b['mu']) < 1e-5 and abs(a['mu_prime']-b['mu_prime']) < 1e-5]
    mac('cleanrows', str(len(clean)))
    fl = [abs(h['psi_first_law']-h['mu_prime']) for _, h, _ in clean]
    mac('firstlawworst', sci(max(fl)))
    mac('firstlawmedian', sci(float(np.median(fl))))
    sm = [abs(h['psi_smarr']-h['mu_prime']) for r, h, _ in clean if r['alpha'] >= 0.05]
    mac('smarrworst', sci(max(sm)))
    mac('smarrmedian', sci(float(np.median(sm))))
    om = [abs(3*h['omega']-(h['mu']-h['y']*h['mu_prime'])) for _, h, _ in clean]
    mac('omegaidclean', sci(max(om)))
    an = json.loads((HERE/'analysis.json').read_text())
    w = an['worst']
    mac('vonedev', sci(w['v1_dev']))
    mac('hHdev', sci(w['hH_dev']))
    mac('sigmanhdev', sci(w['sigma_nh_dev']))
    mac('omegaiddev', sci(w['omega_identity_dev']))
    # slope minimum on the branch
    slope = np.array([h['mu_prime'] for h in hi]); yb = np.array([h['y'] for h in hi])
    i = int(np.argmin(slope))
    mac('slopemin', fx(slope[i], 4))
    mac('slopeminy', fx(yb[i], 3))
    mac('slopelast', fx(slope[-1], 4))
    mac('mugrowth', fx(100*(hi[-1]['mu']/(1.5*np.pi**(1/3))-1), 0))
    # ------------------------------------------------- KKR curve comparison
    kk = json.loads((HERE/'kkr_curves.json').read_text())
    xb = np.array([h['x'] for h in hi]); jb = np.array([h['j'] for h in hi])
    for q, key in (('aH', 'aH'), ('s', 's')):
        qb = np.array([h[key] for h in hi])
        m = np.array(kk[q]['main']); m = m[(m[:, 0] > 0.01) & (m[:, 0] <= xb.max())]
        dev = np.max(np.abs(m[:, 1]-np.interp(m[:, 0], xb, qb)))
        mac(f'kkr{q}dev', sci(dev))
        ins = np.array(kk[q]['inset']); order = np.argsort(jb)
        ins = ins[(ins[:, 0] >= jb.min()) & (ins[:, 0] <= 0.99)]
        dev_j = np.max(np.abs(ins[:, 1]-np.interp(ins[:, 0], jb[order], qb[order])))
        mac(f'kkr{q}devj', sci(dev_j))
    # --------------------------------------------- manuscript comparison
    pol = json.loads((HERE/'polished.json').read_text())
    mac('polishedcouplings', str(len(pol)))
    dmu = [abs(p['value']['mu']-p['manuscript']['mu']) for p in pol]
    dps = [abs(p['value']['mu_prime']-p['manuscript']['psi']) for p in pol]
    dy = [abs(p['value']['y']-p['manuscript']['y']) for p in pol]
    mac('dmuworstms', sci(max(dmu)))
    mac('dpsiworstms', sci(max(dps)))
    mac('dyworstms', sci(max(dy)))
    ratio = [d/p['manuscript']['psi_envelope'] for d, p in zip(dps, pol)]
    mac('psiratioworst', sci(max(ratio)))
    lines = []
    for p in pol:
        v, r, m = p['value'], p['resolution'], p['manuscript']
        lines.append(rf"  ${p['alpha']:g}$ & ${fx(v['y'], 6)}$ & ${fx(v['mu'], 7)}$ & ${sci(r['mu'])}$ & "
                     rf"${fx(m['mu'], 7)}$ & ${sci(m['mu_spread'])}$ & ${fx(v['mu_prime'], 6)}$ & "
                     rf"${sci(r['mu_prime'])}$ & ${fx(m['psi'], 6)}$ & ${sci(m['psi_envelope'])}$ \\")
    L.append(r'\newcommand{\Rcomparisontable}{%')
    L += lines
    L.append('}')
    # ----------------------------------------------------------- gamma check
    gc = json.loads((HERE/'gamma_check.json').read_text()) if (HERE/'gamma_check.json').exists() else []
    if gc:
        mac('gcplateau', str(max(g['fit']['n_range'][1] for g in gc)))
    (OUT/'numbers.tex').write_text('\n'.join(L)+'\n')
    # ------------------------------------------------------------- receipt
    import datetime
    import platform
    import numpy, scipy, sympy
    steps = [
        ('eps\\_digitise.py; kkr\\_curves.py', 'digitised.json, kkr\\_curves.json'),
        ('derive.py', 'equations.pkl (tensor check)'),
        ('nearhorizon.py', 'nearhorizon.json (closed forms, exponents)'),
        ('kkr\\_equations.py 0; pw\\_generator.py 0', 'generated residuals and $J$'),
        ('test\\_rq.py', 'convergence\\_rq.json (gate, resolution study)'),
        ('branch\\_rq.py (two phases)', 'branch\\_rq.json'),
        ('polish\\_couplings.py', 'polished.json'),
        ('analyse\\_branch.py; gamma\\_check.py', 'analysis.json, gamma\\_check.json'),
        ('marimo export html figures\\_kkr.py', 'figures/, figures\\_kkr.html'),
        ('make\\_report\\_numbers.py', 'report/numbers.tex, receipt.tex'),
    ]
    R = [r'\begin{itemize}\itemsep0pt',
         rf'\item date of this build: {datetime.date.today().isoformat()}; directory \texttt{{work/kkr-extremal}}',
         rf'\item environment: Python {platform.python_version()}, NumPy {numpy.__version__}, '
         rf'SciPy {scipy.__version__}, SymPy {sympy.__version__} (project \texttt{{.venv}})']
    R += [rf'\item \texttt{{{c}}} $\to$ {o}' for c, o in steps]
    R.append(r'\end{itemize}')
    (OUT/'receipt.tex').write_text('\n'.join(R)+'\n')
    print(f'wrote report/numbers.tex with {sum(1 for l in L if l.startswith(chr(92)+"newcommand"))} macros')


if __name__ == '__main__':
    main()
