"""Conserved momentum of w, p_w = dL/dw', in the KKR ansatz with radial
coordinate s = r/(1+r) (power 0 of kkr_equations.py), generated as NumPy.

L has no explicit w, so p_w is constant on solutions; at infinity
dL/dw' = -4 W (W the r^-4 coefficient of w) and J = pi W/4 (per plane),
hence J = -(pi/16) p_w. p_w is invariant under radial reparametrisation, so
it can be evaluated in s directly. Asserted: at alpha = 0 on extremal
Myers-Perry (P = 1, W = 0, a = 1) it gives J = pi sqrt(2)/4.

Output: _pw_generated_p0.py with J_of(s, P1..W jets, alpha).
"""
import inspect
import sys
from pathlib import Path

import numpy as np
import sympy as sp

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1]/'experiments'))
from derive_egb_rotating import lagrangians  # noqa: E402
from kkr_equations import ansatz, XI, ALPHA, J as JETS  # noqa: E402


def main(power=0):
    v = lagrangians()
    r = v['r']
    L = v['L_E']+sp.Symbol('alpha_tmp')*v['L_GB']
    p_w = sp.diff(L, sp.diff(v['w'], r))
    funcs, phys = ansatz(power)
    subs = {}
    for k in 'bfghw':
        subs[sp.diff(v[k], r)] = sp.diff(phys[k], XI)
    for k in 'bfghw':
        subs[v[k]] = phys[k]
    e = p_w.subs(subs, simultaneous=True).subs(r, XI).subs(sp.Symbol('alpha_tmp'), ALPHA)
    names = ('P1', 'P2', 'P3', 'W')
    jet_subs = {}
    for n, fn in zip(names, funcs):
        jet_subs[sp.diff(fn, XI)] = JETS[n+'x']
    for n, fn in zip(names, funcs):
        jet_subs[fn] = JETS[n]
    e = e.subs(jet_subs, simultaneous=True)
    Jexpr = -sp.pi/16*e
    args = (XI, JETS['P1'], JETS['P1x'], JETS['P2'], JETS['P2x'], JETS['P3'], JETS['P3x'],
            JETS['W'], JETS['Wx'], ALPHA)
    fn = sp.lambdify(args, Jexpr, modules='numpy', cse=True)
    src = inspect.getsource(fn).replace('def _lambdifygenerated', 'def J_of')
    (HERE/f'_pw_generated_p{power}.py').write_text(
        '"""Generated by pw_generator.py; do not edit."""\nimport numpy as np\n'
        'from numpy import sqrt, pi\n\n'+src)
    sys.path.insert(0, str(HERE))
    module = __import__(f'_pw_generated_p{power}')
    for s in (0.1, 0.4, 0.8):
        val = module.J_of(s, 1., 0., 1., 0., 1., 0., 0., 0., 0.)
        assert abs(val-np.pi*np.sqrt(2)/4) < 1e-12, (s, val)
    print(f'J from p_w on extremal Myers-Perry = pi sqrt(2)/4 at every s: OK; wrote _pw_generated_p{power}.py')


if __name__ == '__main__':
    main(int(sys.argv[1]) if len(sys.argv) > 1 else 0)
