"""Our metric functions against the published curves of fig. 1b of arXiv:1010.0860.

The curves come from the vector paths of the arXiv source EPS, extracted by
`experiments/egb_rotating_paper_eps_profiles.py`; the published file itself is not
redistributed. Left panel: the overlay, at the paper's larger coupling. Right
panel: the difference, which is where the comparison actually lives, against the
width of one device unit of the published figure.

Run from the repository root:
  PYTHONPATH=src python short-summary/make_comparison_figure.py
"""
import json
import os
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
os.environ.setdefault('MPLCONFIGDIR', str(ROOT/'.cache/matplotlib'))

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
DATA = ROOT/'results/egb-rotating-paper-eps-profiles.json'
matplotlib.rcParams.update({
    'font.family': 'serif', 'font.serif': ['DejaVu Serif'],
    'mathtext.fontset': 'cm', 'font.size': 9, 'axes.labelsize': 9.5,
    'legend.fontsize': 8, 'xtick.labelsize': 8.2, 'ytick.labelsize': 8.2,
    'axes.spines.top': False, 'axes.spines.right': False,
    'axes.linewidth': .7, 'lines.linewidth': 1.3, 'pdf.fonttype': 42,
    'figure.dpi': 200,
})
INK, MUTED, GRID = '#0b0b0b', '#898781', '#e1e0d9'
# Categorical slots 1-4 of the validated palette, assigned in fixed order and
# checked with the dataviz validator on a light surface: lightness band, chroma
# floor, CVD separation and normal-vision floor all pass. The contrast warning on
# the last two slots is relieved by the direct labels in the left panel.
SERIES = [
    ('h_over_r2', r'$h/r^2$', '#2a78d6',  7),
    ('f',         r'$f$',     '#eb6834', -7),
    ('w',         r'$w$',     '#1baf7a',  0),
    ('minus_b',   r'$-b$',    '#eda100',  0),
]


def latex_float(value, digits=2):
    text = f'{value:.{digits}e}'
    mantissa, exponent = text.split('e')
    return rf'{mantissa}\times 10^{{{int(exponent)}}}'


def main():
    data = json.loads(DATA.read_text())
    main_set = data['sets']['alpha_paper = 3']
    control = data['sets']['alpha_paper = 0.01']
    rows = {r['field']: r for r in main_set['curves']}
    unit = data['device_unit']

    figure, (left, right) = plt.subplots(1, 2, figsize=(6.0, 2.95))
    for ax in (left, right):
        ax.grid(alpha=.5, linewidth=.55, color=GRID)
        ax.tick_params(length=3, width=.7, colors=INK)
        for spine in ax.spines.values():
            spine.set_color('#c3c2b7')

    left.axhline(0., color=MUTED, linewidth=.7, zorder=1)
    for field, label, colour, offset in SERIES:
        row = rows[field]
        x = np.array(row['log10_r'])
        left.plot(x, row['ours'], color=colour, zorder=3, solid_joinstyle='round')
        left.plot(x, row['published'], linestyle='none', marker='o',
                  markersize=2.6, markerfacecolor='white', markeredgewidth=.8,
                  color=colour, zorder=4)
        left.annotate(label, xy=(x[-1], row['ours'][-1]), xytext=(4, offset),
                      textcoords='offset points', color=colour, va='center',
                      fontsize=9.5, zorder=5)
    left.set_xlabel(r'$\log_{10} r$   (units $r_H=1$)')
    left.set_ylabel('metric functions')
    left.set_xlim(0., 1.33)
    left.legend(handles=[
        plt.Line2D([], [], color=MUTED, linewidth=1.3, label='this work'),
        plt.Line2D([], [], color=MUTED, marker='o', markersize=2.6,
                   markerfacecolor='white', markeredgewidth=.8,
                   linestyle='none', label='published vertices')],
        frameon=False, loc='center right', bbox_to_anchor=(1., .60),
        handlelength=1.5, labelcolor=INK)

    right.axhspan(-unit, unit, color=GRID, zorder=1)
    right.axhline(0., color=MUTED, linewidth=.7, zorder=2)
    for field, label, colour, _ in SERIES:
        row = rows[field]
        right.plot(row['log10_r'],
                   np.array(row['ours'])-np.array(row['published']),
                   color=colour, zorder=3, label=label)
    right.set_xlabel(r'$\log_{10} r$')
    right.set_ylabel('this work $-$ published')
    right.set_xlim(0., 1.26)
    right.legend(frameon=False, ncol=2, loc='lower right', handlelength=1.3,
                 columnspacing=1., labelcolor=INK)
    figure.tight_layout(pad=.4, w_pad=1.8)
    figure.savefig(HERE/'fig-paper-comparison.pdf')
    plt.close(figure)

    analytic = max(r['max_difference_analytic'] for r in control['curves'])
    lines = [
        '% Generated by make_comparison_figure.py; do not edit.',
        rf"\newcommand{{\Cpaperalpha}}{{{main_set['alpha_paper']:g}}}",
        rf"\newcommand{{\Cgbalpha}}{{{main_set['alpha_gb']:g}}}",
        rf"\newcommand{{\Ccontrolalpha}}{{{control['alpha_paper']:g}}}",
        rf"\newcommand{{\Cq}}{{{data['q']:g}}}",
        rf"\newcommand{{\Cvertices}}{{{min(r['points'] for r in main_set['curves'])}}}",
        rf"\newcommand{{\Chorizon}}{{{latex_float(main_set['worst_horizon_difference'])}}}",
        rf"\newcommand{{\Cinterior}}{{{latex_float(main_set['worst_max_difference'])}}}",
        rf"\newcommand{{\Ccontrolinterior}}{{{latex_float(control['worst_max_difference'])}}}",
        rf"\newcommand{{\Canalytic}}{{{latex_float(analytic)}}}",
        rf"\newcommand{{\Cdevice}}{{{latex_float(unit)}}}",
        '',
    ]
    (HERE/'comparison-numbers.tex').write_text('\n'.join(lines), encoding='utf-8')
    print(f"wrote fig-paper-comparison.pdf and comparison-numbers.tex "
          f"(horizon {main_set['worst_horizon_difference']:.2e}, "
          f"interior {main_set['worst_max_difference']:.2e}, "
          f"analytic control {analytic:.2e}, device unit {unit:.2e})")


if __name__ == '__main__':
    main()
